language: ruby
cache: bundler
script: bundle exec middleman build
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
  password:
    secure: ugm7F1PS8Hff8DgBTPx31DT7upEWZ5gWKXSdFvFCa0NyUY0OAL9R4XPTuRaGjbfL/IWZwEiGXElga622SmUK2if66XxDE1kDxRy7ZH7Chg4sw9ybYmudg7fCUCjQbwYuDRCBqqvsAuyoUdtm/Aje9mpT40RLrfXF51G2zGDaS1vqbSl6fckbbVCosOAu2BWOOFEhaCCu+aWjBzrGyctQEYZQtJNquZ7BkgSm5lZF7aPNYYpeWM1kOc7bEKnDMBEq9lN0VH19Kd9zC9yUgdHjlXUZ53yUCC5yPZx07dYE1puL3D0bngm9KhRPlrkAFf9vJpng67rJzBbLVkPF5EUxIp20WL/ZUSWayXGrB9AjtmYRSG80zuLyLm6vCcCoz6YAG078mlgGew5i4phVoyfru78AGVi/fWzcv7hbUlzzX4AFVFWkhUdt4BapdeRWmNfJerS3E/UTMV0FI1xq3mx0cNo+o3Xbcy5exp4ixJnWF6XSfWQ8arI6/cy/aUuzrfcRNrUmaY74D6msHd8jt7hqVFc+jMYHt/rYdnKCaThMt1o1jhwZMnDprmVkAtirQpFc0yk3K/LFLYthLJV7H+eMDQxrX/jnwxiBjd+C7l1MObXgndB7wV3bbydwrzSf2Sb88Oc7z774GXTDHdpUx8kkKbudx80FGUSh6bm3JD1m0Aw=
  organization: govuk-verify
  space: docs
  on:
    repo: alphagov/verify-tech-specs
