# Host to use for canonical URL generation (without trailing slash)

# Header-related options
show_govuk_logo: true
service_name: Verify Technical Specifications
service_link: https://govuk-verify.cloudapps.digital/
phase: TEST

# Links to show on right-hand-side of header
header_links:
  GitHub: https://github.com/alphagov/verify-tech-specs
  Documentation: /

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
#ga_tracking_id:

# google_site_verification:

# Multi-page options
multipage_nav: true
collapsible_nav: true
max_toc_heading_level: 2
enable_search: true
