# Host to use for canonical URL generation (without trailing slash)

# Header-related options
show_govuk_logo: false
service_name: Verify Technical Specifications
service_link: https://govuk-verify.cloudapps.digital/
phase: TEST DEPLOYMENT
prevent_indexing: true

# Links to show on right-hand-side of header
header_links:
  GitHub: https://github.com/alphagov/verify-tech-specs
  Documentation: /

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
#ga_tracking_id:

# google_site_verification:

# Show a block at the bottom of the page that links to the page source, so readers can easily contribute back to the documentation.

show_contribution_banner: true
github_repo: alphagov/verify-tech-specs/

# Multi-page options
multipage_nav: true
collapsible_nav: true
max_toc_heading_level: 3
enable_search: true
